"""Utility sub-package: configuration constants and shared helper functions."""

from collector.utils.config import (
    DEFAULT_LOSS_PER_100KM,
    EARTH_RADIUS_KM,
    GAS_PIPE_OPTIONS,
    GAS_STORAGE_OPTIONS,
    GAS_TERMINAL_OPTIONS,
    GAS_UNIT_FACTOR,
    HYDRO_FILE_TEMPLATES,
    HYDRO_SCALE_FACTOR,
    HYDRO_SHEET_NAMES,
    HYDRO_TARGET_LENGTHS,
    HYDROGEN_PIPE_OPTIONS,
    HYDROGEN_STORAGE_OPTIONS,
    HYDROGEN_TERMINAL_OPTIONS,
    OUTPUT_MODES,
    PECD_FILE_TEMPLATES,
    RESERVE_COLUMNS,
    SOLAR_ROOFTOP_TARGET_LEN,
    TECH_CHAR_COLUMNS,
    TECH_COLUMNS,
    VALID_SCENARIOS,
    FILEPATH_CO2_FACTORS,
    FILEPATH_COMMON_DATA,
    FILEPATH_NETWORKS,
    FILEPATH_STORAGES,
    FILEPATH_TERMINALS,
)
from collector.utils.helpers import (
    build_zone_display_map,
    create_output_directories,
    expand_profile_to_hourly,
    get_co2_usecols,
    get_pemmdb_filepath,
    validate_option,
    validate_scenario,
)

__all__ = [
    # config
    "VALID_SCENARIOS",
    "GAS_PIPE_OPTIONS",
    "HYDROGEN_PIPE_OPTIONS",
    "GAS_STORAGE_OPTIONS",
    "HYDROGEN_STORAGE_OPTIONS",
    "GAS_TERMINAL_OPTIONS",
    "HYDROGEN_TERMINAL_OPTIONS",
    "OUTPUT_MODES",
    "EARTH_RADIUS_KM",
    "DEFAULT_LOSS_PER_100KM",
    "GAS_UNIT_FACTOR",
    "TECH_COLUMNS",
    "TECH_CHAR_COLUMNS",
    "RESERVE_COLUMNS",
    "PECD_FILE_TEMPLATES",
    "HYDRO_FILE_TEMPLATES",
    "HYDRO_SHEET_NAMES",
    "HYDRO_TARGET_LENGTHS",
    "HYDRO_SCALE_FACTOR",
    "SOLAR_ROOFTOP_TARGET_LEN",
    "FILEPATH_CO2_FACTORS",
    "FILEPATH_COMMON_DATA",
    "FILEPATH_NETWORKS",
    "FILEPATH_STORAGES",
    "FILEPATH_TERMINALS",
    # helpers
    "create_output_directories",
    "get_pemmdb_filepath",
    "get_co2_usecols",
    "build_zone_display_map",
    "expand_profile_to_hourly",
    "validate_scenario",
    "validate_option",
]
